// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const missingConfig = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

const createStubClient = (message: string) =>
  new Proxy(
    {},
    {
      get() {
        throw new Error(message);
      },
    }
  ) as unknown as ReturnType<typeof createClient<Database>>;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = missingConfig
  ? createStubClient(
      "Backend config is missing (VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY). Please ensure environment variables are configured for this deployment."
    )
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });

